### ISSUE TITLE
Rust Server reports values in reverse order when requested with get_recent

### ISSUE THREAD

**Issue by Jordanayan** [ACRONYM-Group/ACIRustServer#4]
to remain consistent with how get_recent is handled in Python server and client code so far, Rust Server should return recent list values in the same order they are stored.

**Comment by AshTS** [comment]
Correcting this should be restricted to changing the documentation to reflect the change and removing a `.reverse()` from the handler for the `get_recent` operation.

**Comment by AshTS** [comment]
This change has been implemented in https://github.com/ACRONYM-Group/ACIRustServer/commit/4cc155abd8e922b6d8e9e0f7b5e26cc097806dcarl
