### ISSUE TITLE
Group Commands

### ISSUE THREAD

**Issue by Jordanayan** [ACRONYM-Group/ACIRustServer#5]
As suggested, ACI should have an option to receive group commands as a single websocket packet in order to reduce over head. Group commands would be structured as a list of command dictionaries, and would each be processed separately.

Acknowledgements and responses to group commands would also be grouped into a list (in the same order as the original commands) and then sent to the client.

This greatly reduces the performance impact of sending many ACI commands in a row, especially on low power hardware.

**Comment by AshTS** [comment]
One method of implementing these group commands would be to accept a JSON array as a valid command. This command would then execute each command, returning an array in the same order as the incoming array, with each response. stored within it. Each of these commands should be executed in the order in which they appear in the packed command. 

This should be able to be implemented by checking in an incoming message is a JSON array, if the message is an array it will recursively call a message handling function. This will be done by partially rewriting the `handle_message`  function in `src/connect.rs`.

**Comment by AshTS** [comment]
Implemented in https://github.com/ACRONYM-Group/ACIRustServer/commit/3f30ce856deb8e3119212af62908c6e194588f67.

However, this change does not handle nested packed commands, as such commands should be flattened by the client.
